#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.luci_app_pppoe_server
	set firewall.luci_app_pppoe_server=include
	set firewall.luci_app_pppoe_server.type=script
	set firewall.luci_app_pppoe_server.path=/var/etc/luci-app-pppoe-server.include
	set firewall.luci_app_pppoe_server.reload=1
EOF

rm -rf /tmp/luci-*cache
exit 0
