# Copyright (C) 2020-2026 Hyy2001X <https://github.com/Hyy2001X>

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-shutdown
PKG_VERSION:=2.0
PKG_RELEASE:=1

PKG_LICENSE:=GPL-3.0-or-later

LUCI_TITLE:=LuCI Support for shutdown/reboot
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
