# Adapted from ClashConnectRules/Self-Configuration (MIT).
[custom]
ruleset=🚫 国外广告,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/AdBlock.yaml
ruleset=🚫 国外广告,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/HTTPDNS.yaml
ruleset=DIRECT,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Special.yaml
ruleset=🤖 AI服务,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/AI%20Suite.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Netflix.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Disney%20Plus.yaml
ruleset=📹 YouTube,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/YouTube.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Max.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Spotify.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Bilibili.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/IQ.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/IQIYI.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Letv.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Netease%20Music.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Tencent%20Video.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/WeTV.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Youku.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Abema%20TV.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Bahamut.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/DMM.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Fox%2B.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Hulu%20Japan.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Japonx.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/JOOX.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/KKBOX.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/KKTV.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Line%20TV.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/myTV%20SUPER.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Niconico.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/ViuTV.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/ABC.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Amazon.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/BBC%20iPlayer.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/DAZN.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Discovery%20Plus.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/encoreTVB.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/F1%20TV.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Fox%20Now.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Hulu.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Pandora.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/PBS.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Pornhub.yaml
ruleset=🌍 国外媒体,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Soundcloud.yaml
ruleset=✈️ Telegram,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Telegram.yaml
ruleset=🌐 国际流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Crypto.yaml
ruleset=🌐 国际流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Discord.yaml
ruleset=📧 Google FCM,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Google%20FCM.yaml
ruleset=🔍 谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
ruleset=🔍 谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleDrive/GoogleDrive.yaml
ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTubeMusic/YouTubeMusic.yaml
ruleset=🔍 谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleSearch/GoogleSearch.yaml
ruleset=Ⓜ️ Microsoft,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Microsoft.yaml
ruleset=🌐 国际流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/PayPal.yaml
ruleset=🔍 谷歌服务,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Scholar.yaml
ruleset=🌐 国际流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Speedtest.yaml
ruleset=🌐 国际流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Steam.yaml
ruleset=🌐 国际流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/TikTok.yaml
ruleset=🍎 Apple服务,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Apple%20Music.yaml
ruleset=🍎 Apple服务,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Apple%20News.yaml
ruleset=🍎 Apple服务,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Apple%20TV.yaml
ruleset=🍎 Apple服务,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Apple.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/miHoYo.yaml
ruleset=🌐 国际流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Proxy.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Domestic.yaml
ruleset=🎯 国内流量,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Domestic%20IPs.yaml
ruleset=DIRECT,https://testingcf.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/LAN.yaml
ruleset=🎯 国内流量,[]GEOIP,CN
ruleset=🌐 国际流量,[]FINAL
custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions
custom_proxy_group=🚀 手动切换`select`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 Hong Kong`select`(?i)港|HK|Hong Kong
custom_proxy_group=🇯🇵 Japan`select`(?i)日|JP|Japan
custom_proxy_group=🇺🇸 United States`select`(?i)美|US|United States
custom_proxy_group=🇸🇬 Singapore`select`(?i)新|SG|Singapore
custom_proxy_group=🇹🇼 Taiwan`select`(?i)台|TW|Taiwan
custom_proxy_group=🇰🇷 Korea`select`(?i)韩|KR|Korea
custom_proxy_group=🇬🇧 United Kingdom`select`(?i)英|UK|United Kingdom
custom_proxy_group=🇩🇪 Germany`select`(?i)德|DE|Germany
custom_proxy_group=🇫🇷 France`select`(?i)法|FR|France
custom_proxy_group=🌍 Other Regions`select`^(?!.*((?i)港|HK|Hong Kong|日|JP|Japan|美|US|United States|Balance|新|SG|Singapore|台|TW|Taiwan|韩|KR|Korea|英|UK|United Kingdom|德|DE|Germany|法|FR|France)).*$
custom_proxy_group=🌐 国际流量`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions
custom_proxy_group=🎯 国内流量`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚫 国内广告`select`[]REJECT`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚫 国外广告`select`[]REJECT`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🤖 AI服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions
custom_proxy_group=🔍 谷歌服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions
custom_proxy_group=📧 Google FCM`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions
custom_proxy_group=🍎 Apple服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions`[]DIRECT`.*
custom_proxy_group=✈️ Telegram`select`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇺🇸 United States`[]🇸🇬 Singapore`[]🇹🇼 Taiwan`[]🇰🇷 Korea`[]🇬🇧 United Kingdom`[]🇩🇪 Germany`[]🇫🇷 France`[]🌍 Other Regions
custom_proxy_group=🫧 WeChat`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换
