#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@sqm[-1]
	add ucitrack sqm
	set ucitrack.@sqm[-1].init=sqm
	del_list ucitrack.@firewall[0].affects=sqm
	add_list ucitrack.@firewall[0].affects=sqm
	delete ucitrack.@sqm-autorate[-1]
	add ucitrack sqm-autorate
	set ucitrack.@sqm-autorate[-1].init=sqm-autorate
	del_list ucitrack.@firewall[0].affects=sqm-autorate
	add_list ucitrack.@firewall[0].affects=sqm-autorate
	commit ucitrack
EOF

exit 0
