
include $(TOPDIR)/rules.mk

LUCI_TITLE:=iStoreNAS Login Page
LUCI_DEPENDS:=+luci-theme-argon
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
