#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.luci_app_pptp_server
	set firewall.luci_app_pptp_server=include
	set firewall.luci_app_pptp_server.type=script
	set firewall.luci_app_pptp_server.path=/var/etc/pptpd.include
	set firewall.luci_app_pptp_server.reload=1
EOF

/etc/init.d/pptpd disable 2>/dev/null
/etc/init.d/pptpd stop 2>/dev/null
rm -rf /tmp/luci-*cache
exit 0
