

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0-20221219
PKG_RELEASE:=

LUCI_TITLE:=LuCI support for airconnect
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+airconnect

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

