#!/bin/sh
# 创建必要目录
mkdir -p /etc/nginx/ssl /var/www/acme
chmod 750 /etc/nginx/ssl
chmod 755 /var/www/acme
chown www-data:www-data /var/www/acme

# 设置默认日志权限
touch /var/log/nginx/proxy.log
chown www-data:adm /var/log/nginx/proxy.log

exit 0
