# Copyright (C) 2020-2022 Hyy2001X <https://github.com/Hyy2001X>

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-autoupdate
PKG_VERSION:=9
PKG_RELEASE:=3

LUCI_TITLE:=LuCI Support for autoupdate
LUCI_DEPENDS:=+autoupdate
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
