#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=95
USE_PROCD=1

PROG=/usr/libexec/natflow-simple-qos
NAME=natflow-simple-qos

start_service() {
	[ -c /dev/userinfo_ctl ] || return 0
	[ -c /dev/userinfo_event_ctl ] || return 0
	[ -x "$PROG" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" run
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

reload_service() {
	restart "$@"
}

service_triggers() {
	procd_add_reload_trigger natflow
}
