#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034

START=95
STOP=05
USE_PROCD=1

PROG=/usr/libexec/natflow-userinfo-eventd

start_service() {
	[ -c /dev/natflow_userinfo_ctl ] || return 0
	[ -c /dev/natflow_userinfo_queue ] || return 0
	[ -x "$PROG" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param term_timeout 5
	procd_set_param stderr 1
	procd_close_instance
}

service_stopped() {
	ACTION=stop USERINFO_VERSION=3 /sbin/hotplug-call userinfo
}

reload_service() {
	ACTION=reload USERINFO_VERSION=3 /sbin/hotplug-call userinfo
}

service_triggers() {
	procd_add_reload_trigger natflow
}
