# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2023 ImmortalWrt.org

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for FileBrowser
LUCI_DEPENDS:=+filebrowser

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
