#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autotimeset[-1]
	add ucitrack autotimeset
	set ucitrack.@autotimeset[-1].init=autotimeset
	commit ucitrack
EOF
chmod 755 /etc/init.d/autotimeset  >/dev/null 2>&1
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache*
exit 0
