package model

import "time"

// SubscriptionSource is a user-managed subscription endpoint.
type SubscriptionSource struct {
	ID                   string             `json:"id"`
	Name                 string             `json:"name"`
	URL                  string             `json:"url"`
	Enabled              bool               `json:"enabled"`
	CreatedAt            time.Time          `json:"created_at"`
	LastUpdatedAt        *time.Time         `json:"last_updated_at,omitempty"`
	LastError            string             `json:"last_error,omitempty"`
	Usage                *SubscriptionUsage `json:"usage,omitempty"`
	RequestOptions       *RequestOptions    `json:"request_options,omitempty"`
	NameWasAutoGenerated *bool              `json:"name_was_auto_generated,omitempty"`
}

// RequestOptions carries optional request identity and resolver overrides for
// airports that reject generic clients.
type RequestOptions struct {
	UserAgent       string `json:"user_agent,omitempty"`
	DNSOverHTTPSURL string `json:"dns_over_https_url,omitempty"`
}

// SubscriptionUsage records plan quota reported by the airport.
type SubscriptionUsage struct {
	UploadBytes   int64      `json:"upload_bytes,omitempty"`
	DownloadBytes int64      `json:"download_bytes,omitempty"`
	TotalBytes    int64      `json:"total_bytes,omitempty"`
	ExpiresAt     *time.Time `json:"expires_at,omitempty"`
}
