
include $(TOPDIR)/rules.mk

LUCI_TITLE:=ua2f for luci
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=5.2
PKG_RELEASE:=5

include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
