#!/bin/sh /etc/rc.common

START=98

boot() {
    # /usr/bin/mountpoint -q /CloudNAS || /usr/bin/mount --make-shared -t tmpfs -o size=4M tmpfs /CloudNAS
    [ -d /mnt/CloudNAS ] || mkdir -p /mnt/CloudNAS
    if /usr/bin/mountpoint -q /mnt; then
        /usr/bin/mount --make-shared /mnt
    else
        /usr/bin/mount --make-shared -t tmpfs -o size=4M tmpfs /mnt/CloudNAS
    fi
}
