include $(TOPDIR)/rules.mk

PKG_VERSION:=1.1.1
PKG_RELEASE:=20221115
PKG_MAINTAINER:=xiaobao <xiaobao@linkease.com>

LUCI_TITLE:=LuCI library for json form
LUCI_DESCRIPTION:=Json form library

LUCI_DEPENDS:= +luci-lib-jsonc
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

