

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0-1
PKG_RELEASE:=
PKG_MAINTAINER:=jjm2473 <jjm2473@gmail.com>

LUCI_TITLE:=LuCI realtime client bandwidth monitor
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+iptables

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
