#!/bin/sh

[ -f /usr/share/honk/download_dashboard.sh ] && chmod +x /usr/share/honk/download_dashboard.sh
[ -f /usr/share/honk/download_zashboard.sh ] && rm -f /usr/share/honk/download_zashboard.sh

rm -rf /tmp/luci-*
/etc/init.d/rpcd reload 2>/dev/null

exit 0

