#!/bin/sh

# Background commands must not inherit the setup lock from their parent.
[ -z "$1" ] || exec 9>&-

. /lib/functions.sh
. /lib/functions/network.sh

worker_current()
{
	local current_generation
	read -r current_generation < /tmp/fakemesh.generation 2>/dev/null || return 1
	[ "$FAKEMESH_GENERATION" = "$current_generation" ]
}

worker_unlock()
{
	[ -n "$worker_dir" ] || return 0
	rm -f "$worker_dir/$$"
	rmdir "$worker_dir" 2>/dev/null
	worker_dir=
}

worker_cleanup()
{
	worker_unlock
	[ -z "$sync_tmp" ] || rm -f "$sync_tmp"
}

worker_lock()
{
	worker_current || return 1
	mkdir -m 700 "$1" 2>/dev/null || return 1
	worker_dir="$1"
	touch "$worker_dir/$$"
	trap 'worker_cleanup' EXIT
	trap 'exit 0' HUP INT TERM
	worker_current || { worker_cleanup; return 1; }
}

is_worker()
{
	local command_line
	[ "$1" != "$$" ] && [ -r "/proc/$1/cmdline" ] || return 1
	command_line=$(tr '\000' ' ' < "/proc/$1/cmdline")
	case " $command_line " in
		*" /usr/sbin/fakemesh "*) return 0 ;;
	esac
	return 1
}

stop_workers()
{
	local marker worker_pid pending= waited=0
	for marker in /tmp/fakemesh_lck[1-7]/*; do
		[ -f "$marker" ] || continue
		worker_pid=${marker##*/}
		case "$worker_pid" in ''|*[!0-9]*) continue ;; esac
		is_worker "$worker_pid" || continue
		kill -TERM "$worker_pid" 2>/dev/null
		pending="$pending $worker_pid"
	done
	while [ -n "$pending" ]; do
		local alive=
		for worker_pid in $pending; do
			is_worker "$worker_pid" || continue
			if [ "$waited" -ge 15 ]; then
				kill -KILL "$worker_pid" 2>/dev/null
			fi
			alive="$alive $worker_pid"
		done
		pending=$alive
		[ -z "$pending" ] && break
		sleep 1
		waited=$((waited+1))
	done
	rm -rf /tmp/fakemesh_lck[1-7]
}

setup_lock()
{
	exec 9>/var/lock/fakemesh.lock
	flock -x 9 || return 1
	trap 'flock -u 9' EXIT
	trap 'exit 1' HUP INT TERM
}

case "$1" in
	setup) exit 0 ;;
	'')
		setup_lock || exit 1
		FAKEMESH_GENERATION="$$.$(date +%s)"
		printf '%s\n' "$FAKEMESH_GENERATION" > /tmp/fakemesh.generation
		export FAKEMESH_GENERATION
		stop_workers
		;;
	*)
		if [ -z "$FAKEMESH_GENERATION" ]; then
			read -r FAKEMESH_GENERATION < /tmp/fakemesh.generation 2>/dev/null || exit 0
		fi
		export FAKEMESH_GENERATION
		worker_current || exit 0
		;;
esac

band_steer_helper=${band_steer_helper:-$(uci -q get fakemesh.default.band_steer_helper 2>/dev/null)}
band_steer_helper=${band_steer_helper:-none}

unified_ssid_exists()
{
	local s2 s5 ssid2 ssid5
	for s2 in $1; do
		config_get ssid2 "$s2" ssid
		[ -n "$ssid2" ] || continue
		for s5 in $2; do
			config_get ssid5 "$s5" ssid
			[ "$ssid2" = "$ssid5" ] && return 0
		done
	done
	return 1
}

collect_band_ifaces()
{
	local mode dev radio_band ssid
	config_get mode "$1" mode
	[ "$mode" = ap ] || return 0
	config_get dev "$1" device
	config_get radio_band "$dev" band
	config_get ssid "$1" ssid
	[ -n "$ssid" ] || return 0
	case "$radio_band" in
		2g|2.4g|2.4G) ssid_2g="$ssid_2g $1" ;;
		5g|5G|6g|6G) ssid_5g="$ssid_5g $1" ;;
	esac
}

wireless_has_unified_ssid()
(
	config_load wireless || exit 1
	ssid_2g=
	ssid_5g=
	config_foreach collect_band_ifaces wifi-iface
	unified_ssid_exists "$ssid_2g" "$ssid_5g"
)

band_steer_helper_switch()
{
	[ "$(uci -q get fakemesh.default.enabled 2>/dev/null)" = "1" ] || return 0
	worker_lock /tmp/fakemesh_lck6 || return 0

	if [ "$band_steer_helper" = "usteer" ]; then
		uci delete usteer.@usteer[0].event_log_types 2>/dev/null
		uci delete usteer.@usteer[0].ssid_list 2>/dev/null

		# Auto-detect dual-band SSID topology
		if wireless_has_unified_ssid; then
			uci -q set usteer.@usteer[0].band_steering_min_snr='-72'
			uci -q set usteer.@usteer[0].band_steering_interval='30000'
		else
			uci -q set usteer.@usteer[0].band_steering_min_snr='0'
			uci -q set usteer.@usteer[0].band_steering_interval='0'
		fi

		uci commit usteer
		test -x /etc/init.d/dawn && {
			/etc/init.d/dawn enabled && /etc/init.d/dawn disable
			/etc/init.d/dawn running && /etc/init.d/dawn stop
		}
		test -x /etc/init.d/usteer && {
			/etc/init.d/usteer enabled || /etc/init.d/usteer enable
			/etc/init.d/usteer running || /etc/init.d/usteer start
		}
	elif [ "$band_steer_helper" = "dawn" ]; then
		test -x /etc/init.d/usteer && {
			/etc/init.d/usteer enabled && /etc/init.d/usteer disable
			/etc/init.d/usteer running && /etc/init.d/usteer stop
		}
		test -x /etc/init.d/dawn && {
			/etc/init.d/dawn enabled || /etc/init.d/dawn enable
			/etc/init.d/dawn running || /etc/init.d/dawn start
		}
	else
		test -x /etc/init.d/dawn && {
			/etc/init.d/dawn enabled && /etc/init.d/dawn disable
			/etc/init.d/dawn running && /etc/init.d/dawn stop
		}
		test -x /etc/init.d/usteer && {
			/etc/init.d/usteer enabled && /etc/init.d/usteer disable
			/etc/init.d/usteer running && /etc/init.d/usteer stop
		}
	fi
}

[ "x$1" = "xband_steer_helper_switch" ] && {
	band_steer_helper_switch
	exit 0
}

[ "x$1" = "xsetup" ] && {
	exit 0
}

config_load fakemesh

config_get_bool enabled default 'enabled' '0'

test $enabled -eq 0 && {
	[ -z "$1" ] || exit 0
	rm -f /www/fakemesh.*
	rm -f /tmp/fakemesh.firewall.include

	test -e /etc/init.d/umdns && {
	rm /tmp/fakemesh.umdns.json 2>/dev/null && \
	/etc/init.d/umdns restart
	}

	uci delete wireless.meshx0 >/dev/null 2>&1
	uci delete wireless.meshx1 >/dev/null 2>&1

	I=0
	while uci get wireless.@wifi-iface[$I] >/dev/null 2>&1; do
		echo "$(uci get wireless.@wifi-iface[$I].network)" | grep -q "^meshx" && {
			uci set wireless.@wifi-iface[$I].network="lan"
		}
		I=$((I+1))
	done

	uci delete fakemesh.default.wifim_md5 >/dev/null 2>&1
	uci delete dhcp.meshx0 >/dev/null 2>&1
	uci delete network.meshx0 >/dev/null 2>&1
	uci delete network.meshx0_6 >/dev/null 2>&1
	uci delete firewall.fakemesh >/dev/null 2>&1
	sed -i "/.* controller.fakemesh/d" /etc/hosts
	sed -i "/sh \/usr\/share\/fakemesh\/firewall.include.*/d" /etc/firewall.include

	#re-enable lan
	uci delete network.lan.auto >/dev/null 2>&1
	#re-enable wan
	uci delete network.wan.auto >/dev/null 2>&1
	uci delete network.wan6.auto >/dev/null 2>&1
	#del wan port from br-lan
	lan_idx=0
	while uci get network.@device[$lan_idx] >/dev/null 2>&1 && [ "$(uci get network.@device[$lan_idx].name)" != "br-lan" ]; do lan_idx=$((lan_idx+1)); done
	lan_ports="$(uci get network.@device[$lan_idx].ports 2>/dev/null)"
	wan_port="$(uci get network.wan.device 2>/dev/null)"
	newlan_ports=$(for lp in $lan_ports; do [ "$lp" = "$wan_port" ] || echo "$lp"; done | sort | uniq)
	newlan_ports=$(printf "%s\n" "$newlan_ports" | awk '{ for (i = 1; i <= NF; i++) out = out (out ? " " : "") $i } END { print out }')
	[ "$lan_ports" != "$newlan_ports" ] && {
		uci delete network.@device[$lan_idx].ports >/dev/null 2>&1
		for lp in $newlan_ports; do
			uci add_list network.@device[$lan_idx].ports="$lp"
		done
	}

	#delete meshx0 from lan zone
	lan_idx=0
	while uci get firewall.@zone[$lan_idx] >/dev/null 2>&1 && [ "$(uci get firewall.@zone[$lan_idx].name)" != "lan" ]; do lan_idx=$((lan_idx+1)); done
	lan_net="$(uci get firewall.@zone[$lan_idx].network 2>/dev/null)"
	newlan_net=$(for ln in $lan_net; do [ "$ln" = "meshx0" ] || [ "$ln" = "meshx0_6" ] || echo "$ln"; done | sort | uniq)
	newlan_net=$(printf "%s\n" "$newlan_net" | awk '{ for (i = 1; i <= NF; i++) out = out (out ? " " : "") $i } END { print out }')
	[ "$lan_net" != "$newlan_net" ] && {
		uci delete firewall.@zone[$lan_idx].network >/dev/null 2>&1
		for ln in $newlan_net; do
			uci add_list firewall.@zone[$lan_idx].network="$ln"
		done
		uci commit firewall
	}

	uci changes

	uci commit fakemesh
	uci commit wireless
	uci commit dhcp
	uci commit firewall
	uci commit network
	/etc/init.d/network reload
	/etc/init.d/dnsmasq reload
	/etc/init.d/firewall reload >/dev/null 2>&1
	exit 0
}

config_get role default 'role' 'agent'
config_get band default 'band' '5g'
config_get Xid default 'id'
config_get Xkey default 'key'
config_get access_ip default 'access_ip' '10.10.10.1'
config_get sync_ac default 'sync_ac' '1'
config_get fronthaul_disabled default 'fronthaul_disabled' '0'

lost_ac=${lost_ac:-0}
LOST_AC_CNT=3

agent_lost_ac()
{
	[ "$role" = "agent" ] || [ "$role" = "wap" ] || return 0
	worker_lock /tmp/fakemesh_lck4 || return 0

	pid=$$
	logger -t fakemesh "agent_lost_ac($pid): started! lost_ac=$lost_ac"

	if test $lost_ac -gt $LOST_AC_CNT; then
		worker_unlock
		lost_ac=$lost_ac exec /usr/sbin/fakemesh agent_sync_config &
		return 0
	fi

	#re-enable lan
	uci delete network.lan.auto >/dev/null 2>&1
	uci set network.lan.ipaddr="192.168.16.1"
	for lip in `seq 16 20`; do
		if ip route | grep -q "192.168.$lip.0/"; then
			:
		else
			uci set network.lan.ipaddr="192.168.$lip.1"
			break
		fi
	done
	uci set network.lan.netmask='255.255.255.0'
	logger -t fakemesh "agent_lost_ac($pid): setup temporary lan ip=$(uci get network.lan.ipaddr)"

	#re-enable lan enable wifi
	ssid="$(uci get base_config.@status[0].SSID)@$(uci get network.lan.ipaddr)"
	ssid_passwd=$(uci get base_config.@status[0].SSID_PASSWD)
	K=0
	for band in 2g 5g; do
		wbandstr=$(uci show wireless | grep ".band='${band}'$" -m1)
		if test -n "$wbandstr"; then
			radio=$(echo "$wbandstr" | cut -d. -f2)

			uci set wireless.wifinet$K=wifi-iface
			uci set wireless.wifinet$K.device="${radio}"
			uci set wireless.wifinet$K.network='lan'
			uci set wireless.wifinet$K.mode='ap'
			uci set wireless.wifinet$K.ssid="${ssid}"
			uci set wireless.wifinet$K.encryption="psk2"
			uci set wireless.wifinet$K.key="${ssid_passwd}"
			uci set wireless.wifinet$K.wpa_group_rekey='601'
			uci set wireless.wifinet$K.max_inactivity='301'
			if uci get wireless.${radio}.path | grep -q bcma || iwinfo wlan${radio:5} info | grep -qi Cypress; then
				WLAN_IDX=${radio:5}
				uci set wireless.wifinet$K.ifname="wlan${WLAN_IDX}"
			else
				uci set wireless.wifinet$K.ieee80211r='1'
				uci set wireless.wifinet$K.ft_over_ds='0'
				uci set wireless.wifinet$K.ft_psk_generate_local='1'
			fi

			uci delete wireless.wifinet$K.disabled 2>/dev/null
			K=$((K+1))
			logger -t fakemesh "agent_lost_ac($pid): starting wifi SSID=\'${ssid}\' on ${radio} $band!"
		fi
	done
	while uci get wireless.wifinet$K 2>/dev/null; do
		uci set wireless.wifinet$K.disabled='1'
		K=$((K+1))
	done

	nft_add_brmeshfilters() {
		brif="$1"
		nft add table netdev brmeshfilters_$brif 2>/dev/null
		nft "add chain netdev brmeshfilters_$brif devfilter { type filter hook ingress device $brif priority 0 ; }" 2>/dev/null
		nft add rule netdev brmeshfilters_$brif devfilter udp sport 68 drop 2>/dev/null
	}

	#drop all in-comming DHCP request from eth port
	for brif in $(cd /sys/class/net/br-lan/brif/ && ls); do
		iwinfo $brif info >/dev/null 2>&1 && [ "$brif" != "meshx0" ] && [ "$brif" != "meshx1" ] && continue
		nft_add_brmeshfilters $brif
	done

	#dhcp no push router for lan, no push dns for lan
	uci add_list dhcp.lan.dhcp_option='option:router'
	uci add_list dhcp.lan.dhcp_option='6'

	/etc/init.d/network reload
	/etc/init.d/dnsmasq reload
	sleep 5
	uci revert dhcp
	uci revert network
	uci revert wireless

	#drop all in-comming DHCP request from eth port
	#XXX: since network reload, netdevice may unregister and re-create, it is safe to re-add filter rules again.
	for brif in $(cd /sys/class/net/br-lan/brif/ && ls); do
		iwinfo $brif info >/dev/null 2>&1 && [ "$brif" != "meshx0" ] && [ "$brif" != "meshx1" ] && continue
		nft_add_brmeshfilters $brif
	done

	logger -t fakemesh "agent_lost_ac($pid): done!"

	worker_unlock
	lost_ac=$lost_ac exec /usr/sbin/fakemesh agent_sync_config &
}

controller_addresses()
(
	. /usr/share/libubox/jshn.sh
	json_load "$(ubus call umdns browse)" || exit 1
	json_select "_fakemesh_${Xid}._tcp" || exit 1
	json_get_keys services
	for service in $services; do
		json_select "$service" || continue
		json_get_var address ipv4
		[ -z "$address" ] || printf '%s\n' "$address"
		json_select ..
	done
)

controller_announcement()
(
	. /usr/share/libubox/jshn.sh
	json_init
	json_add_object fakemesh
	json_add_string service "_fakemesh_${Xid}._tcp.local"
	json_add_int port 65535
	json_add_array txt
	json_add_string '' "id=${Xid}"
	json_close_array
	json_close_object
	json_dump
)

wireless_config_md5()
{
	local digest
	digest=$({
		printf 'role=%s\n' "$1"
		uci show fakemeshac | grep '^fakemeshac.@wifim'
	} | md5sum)
	printf '%s' "${digest%% *}"
}

collect_radios()
{
	local radio_band radio_path
	config_get radio_band "$1" band
	case "$radio_band" in
		2g) radios_2g="$radios_2g $1" ;;
		5g) radios_5g="$radios_5g $1" ;;
		6g) radios_6g="$radios_6g $1" ;;
		*) return 0 ;;
	esac
	config_get radio_path "$1" path
	case "$radio_path" in
		*bcma*) legacy_radios="$legacy_radios $1" ;;
		*)
			if iwinfo "wlan${1#radio}" info 2>/dev/null | grep -qi Cypress; then
				legacy_radios="$legacy_radios $1"
			fi
			;;
	esac
}

validate_ac_config()
(
	validate_dir="/tmp/fakemesh-validate.$$"
	mkdir -m 700 "$validate_dir" || exit 1
	trap 'rm -rf "$validate_dir"' EXIT
	cp "$1" "$validate_dir/fakemeshac" || exit 1

	# Parse independently of the live config and any pending UCI changes.
	config_dump=$(uci -q -c "$validate_dir" -P "$validate_dir" show fakemeshac) || exit 1
	ac_get() {
		uci -q -c "$validate_dir" -P "$validate_dir" get "$1"
	}
	[ "$(ac_get fakemeshac.default)" = "fakemesh" ] || exit 1
	[ "$(ac_get fakemeshac.default.role)" = "controller" ] || exit 1
	[ "$(ac_get fakemeshac.default.enabled)" = "1" ] || exit 1
	mesh_id=$(ac_get fakemeshac.default.id)
	[ -n "$mesh_id" ] && [ "${#mesh_id}" -le 32 ] || exit 1
	case "$(ac_get fakemeshac.default.band)" in
		2g|5g|6g) ;;
		*) exit 1 ;;
	esac

	# An explicitly empty wireless catalog is valid, but malformed entries are not.
	sections=$(printf '%s\n' "$config_dump" | sed -n 's/^\(fakemeshac\.[^.]*\)=wifim$/\1/p')
	for section in $sections; do
		ssid=$(ac_get "$section.ssid")
		[ -n "$ssid" ] && [ "${#ssid}" -le 32 ] || exit 1
		case "$(ac_get "$section.band")" in
			2g|5g|6g|2g5g|2g6g|5g6g|2g5g6g) ;;
			*) exit 1 ;;
		esac
		case "$(ac_get "$section.enabled" || printf 1)" in
			0|1) ;;
			*) exit 1 ;;
		esac
		case "$(ac_get "$section.encryption")" in
			none|owe) ;;
			psk|psk2|psk-mixed|sae|sae-mixed)
				key=$(ac_get "$section.key")
				[ -n "$key" ] || exit 1
				;;
			*) exit 1 ;;
		esac
	done
	exit 0
)

agent_sync_config()
{
	[ "$sync_ac" = "1" ] || {
		return 0
	}
	worker_lock /tmp/fakemesh_lck3 || return 0
	pid=$$
	sync_tmp="/tmp/fakemesh.ac.config.tmp.$pid"

	logger -t fakemesh "agent_sync_config($pid): started!"
	hash=$(echo -n ${Xid}${Xkey} | md5sum)
	hash=${hash%% *}
	validated_config=0

	touch /tmp/fakemesh.ac.config
	ln -s /tmp/fakemesh.ac.config /etc/config/fakemeshac 2>/dev/null

	while :; do
		[ "$role" != "controller" ] && {
			if test $lost_ac -gt 2; then
				ubus call network.interface.meshx0 down
				sleep 1
				ubus call network.interface.meshx0 up
				sleep 1
			fi
			ubus -t 15 wait_for network.interface.meshx0
		}
		sleep 15
		achost=controller.fakemesh
		if [ "$role" != "controller" ]; then
			if test $lost_ac -gt 0; then
				/etc/init.d/umdns reload
				sleep 5
			fi
			achost=$(controller_addresses)
			if ! test -n "$achost"; then
				logger -t fakemesh "agent_sync_config($pid): umdns: achost not found(lost_ac=$lost_ac)!"
				achost=controller.fakemesh
			fi
			acnum=$(echo -n "$achost" | wc -w)
			if [ "$acnum" -gt 1 ]; then
				logger -t fakemesh "agent_sync_config($pid): umdns: achost found $acnum($achost)(lost_ac=$lost_ac)!"
				rand=$(hexdump -e '"%u"' -n1 /dev/urandom)
				rand=$(((rand % acnum) + 1))
				achost=$(for w in $achost; do echo $w; done | head -n$rand | tail -n1)
				logger -t fakemesh "agent_sync_config($pid): umdns: achost found random select($achost)(lost_ac=$lost_ac)!"
			fi
		fi

		if ( \
		[ "$role" = "controller" ] && cp /etc/config/fakemesh "$sync_tmp" || \
		wget -4 -q -T 10 -t 1 -O "$sync_tmp" http://$achost/fakemesh.$hash 2>/dev/null ); then
			:
		else
			lost_ac=$((lost_ac+1))
			logger -t fakemesh "agent_sync_config($pid): fetch config from $achost failed($lost_ac)!"
			acip=$(ip route | grep "default via" -m1 | awk '{print $3}')
			if test -n "$acip" && ifconfig br-lan | grep -q "addr:$acip "; then
				logger -t fakemesh "agent_sync_config($pid): acip=$acip is setup on br-lan(lost_ac=$lost_ac)!"
				ubus call network.interface.lan down
				/etc/init.d/network reload
				sleep 5
			fi
			if test -n "$acip" && [ "$role" != "controller" ] && wget -4 -q -T 5 -t 1 -O "$sync_tmp" http://$acip/fakemesh.$hash 2>/dev/null; then
				logger -t fakemesh "agent_sync_config($pid): fetch config from gateway($acip) ok(lost_ac=$lost_ac)"
			elif test -n "$achost" && [ "$role" != "controller" ] && wget -4 -q -T 5 -t 1 -O "$sync_tmp" http://$achost/fakemesh.$hash 2>/dev/null; then
				logger -t fakemesh "agent_sync_config($pid): fetch config from achost($achost) ok(lost_ac=$lost_ac)"
			else
				if test $lost_ac -ge $LOST_AC_CNT; then
					worker_unlock
					lost_ac=$lost_ac exec /usr/sbin/fakemesh agent_lost_ac &
					return 0
				fi
				logger -t fakemesh "agent_sync_config($pid): fetch config from achost($achost)/gateway($acip) failed($lost_ac), wait 30s"
				sleep 30
				rm -f "$sync_tmp"
				test -f /tmp/fakemesh_lck3/$pid || return 0
				continue
			fi
		fi

		worker_current || return 0
		if { [ "$validated_config" != 1 ] || ! cmp -s "$sync_tmp" /tmp/fakemesh.ac.config; } && ! validate_ac_config "$sync_tmp"; then
			lost_ac=$((lost_ac+1))
			logger -t fakemesh "agent_sync_config($pid): invalid controller config ($lost_ac), keeping current config"
			rm -f "$sync_tmp"
			if [ "$role" != "controller" ] && test "$lost_ac" -ge "$LOST_AC_CNT"; then
				worker_unlock
				lost_ac=$lost_ac exec /usr/sbin/fakemesh agent_lost_ac &
				return 0
			fi
			sleep 30
			test -f /tmp/fakemesh_lck3/$pid || return 0
			continue
		fi

		worker_current || return 0
		mv "$sync_tmp" /tmp/fakemesh.ac.config || return 1
		validated_config=1

		# Dynamic usteer parameters synchronization & hitless reload
		new_min_snr=$(uci -q get fakemeshac.default.min_snr)
		new_roam_trigger=$(uci -q get fakemeshac.default.roam_trigger_snr)
		new_roam_scan=$(uci -q get fakemeshac.default.roam_scan_snr)
		new_min_connect=$(uci -q get fakemeshac.default.min_connect_snr)
		new_signal_diff=$(uci -q get fakemeshac.default.signal_diff_threshold)
		new_load_kick=$(uci -q get fakemeshac.default.load_kick_enabled)
		if [ -n "$new_min_snr" ]; then
			old_min_snr=$(uci -q get usteer.@usteer[0].min_snr)
			old_roam_trigger=$(uci -q get usteer.@usteer[0].roam_trigger_snr)
			old_roam_scan=$(uci -q get usteer.@usteer[0].roam_scan_snr)
			old_min_connect=$(uci -q get usteer.@usteer[0].min_connect_snr)
			old_signal_diff=$(uci -q get usteer.@usteer[0].signal_diff_threshold)
			old_load_kick=$(uci -q get usteer.@usteer[0].load_kick_enabled)
			if [ "$old_min_snr" != "$new_min_snr" ] || [ "$old_roam_trigger" != "$new_roam_trigger" ] || \
			   [ "$old_roam_scan" != "$new_roam_scan" ] || [ "$old_min_connect" != "$new_min_connect" ] || \
			   [ "$old_signal_diff" != "$new_signal_diff" ] || [ "$old_load_kick" != "$new_load_kick" ]; then
				[ -n "$new_min_snr" ] && uci -q set usteer.@usteer[0].min_snr="$new_min_snr"
				[ -n "$new_roam_trigger" ] && uci -q set usteer.@usteer[0].roam_trigger_snr="$new_roam_trigger"
				[ -n "$new_roam_scan" ] && uci -q set usteer.@usteer[0].roam_scan_snr="$new_roam_scan"
				[ -n "$new_min_connect" ] && uci -q set usteer.@usteer[0].min_connect_snr="$new_min_connect"
				[ -n "$new_signal_diff" ] && uci -q set usteer.@usteer[0].signal_diff_threshold="$new_signal_diff"
				[ -n "$new_load_kick" ] && uci -q set usteer.@usteer[0].load_kick_enabled="$new_load_kick"
				uci commit usteer
				if ubus -S list usteer >/dev/null 2>&1; then
					ubus call usteer reload 2>/dev/null || /etc/init.d/usteer reload 2>/dev/null
				fi
			fi
		fi

		test $lost_ac -gt 0 && logger -t fakemesh "agent_sync_config($pid): fetch config ok!"

		oldbsh=$(uci -q get fakemesh.default.band_steer_helper 2>/dev/null || echo none)
		newbsh=$(uci -q get fakemeshac.default.band_steer_helper 2>/dev/null || echo none)
		[ "${oldbsh}" = "${newbsh}" ] || {
			uci set fakemesh.default.band_steer_helper="${newbsh}"
			uci commit fakemesh
			band_steer_helper="${newbsh}" exec /usr/sbin/fakemesh band_steer_helper_switch &
		}

		oldcfgmd5=$(uci get fakemesh.default.wifim_md5 2>/dev/null)
		newcfgmd5=$(wireless_config_md5 "$role")
		[ "${oldcfgmd5}" = "${newcfgmd5}" ] || {
			logger -t fakemesh "agent_sync_config($pid): config change!"
			# Radio metadata and driver/package capabilities do not vary per SSID.
			config_load wireless
			radios_2g= radios_5g= radios_6g= legacy_radios=
			config_foreach collect_radios wifi-device
			basic_wpad=0
			if opkg list-installed 2>/dev/null | grep -q wpad-basic || apk list 2>/dev/null | grep wpad-basic | grep -q installed; then
				basic_wpad=1
			fi
			#delete old wifi config
			I=0
			while uci get wireless.@wifi-iface[$I] >/dev/null 2>&1; do
				if uci show wireless.@wifi-iface[$I] | grep -q wireless.meshx[01]=wifi-iface; then
					I=$((I+1))
					continue
				fi
				uci delete wireless.@wifi-iface[$I] >/dev/null 2>&1
			done

			J=0
			K=0
			while uci get fakemeshac.@wifim[$J] >/dev/null 2>&1; do
				ssid=$(uci get fakemeshac.@wifim[$J].ssid)
				encryption=$(uci get fakemeshac.@wifim[$J].encryption)
				key=$(uci get fakemeshac.@wifim[$J].key)
				bands=$(uci get fakemeshac.@wifim[$J].band)
				enabled=$(uci get fakemeshac.@wifim[$J].enabled || echo 1)

				[ "$bands" = "2g5g" ] && bands="2g 5g"
				[ "$bands" = "2g5g6g" ] && bands="2g 5g 6g"
				[ "$bands" = "5g6g" ] && bands="5g 6g"
				[ "$bands" = "2g6g" ] && bands="2g 6g" 

				[ "$enabled" = "1" ] && {
					for band in $bands; do
						case "$band" in
							2g) radios=$radios_2g ;;
							5g) radios=$radios_5g ;;
							6g) radios=$radios_6g ;;
							*) radios= ;;
						esac
						for radio in $radios; do

							uci set wireless.wifinet$K=wifi-iface
							uci set wireless.wifinet$K.device="${radio}"
							if [ "$role" = "controller" ]; then
								uci set wireless.wifinet$K.network='lan'
							else
								uci set wireless.wifinet$K.network='meshx0'
							fi
							uci set wireless.wifinet$K.mode='ap'
							uci set wireless.wifinet$K.ssid="${ssid}"
							uci set wireless.wifinet$K.wpa_group_rekey='601'
							uci set wireless.wifinet$K.max_inactivity='301'
							if [ "${encryption}" != "none" ]; then
								if [ "$band" = "6g" ]; then
									case "${encryption}" in
										sae|sae-mixed|owe)
											uci set wireless.wifinet$K.encryption="${encryption}"
											;;
										*)
											uci set wireless.wifinet$K.encryption="sae"
											;;
									esac
									uci set wireless.wifinet$K.ieee80211w='2'
								else
									uci set wireless.wifinet$K.encryption="${encryption}"
									case "${encryption}" in
										sae)
											uci set wireless.wifinet$K.ieee80211w='2'
											;;
										sae-mixed)
											uci set wireless.wifinet$K.ieee80211w='1'
											;;
									esac
								fi
								uci set wireless.wifinet$K.key="${key}"
							else
								if [ "$band" = "6g" ]; then
									uci set wireless.wifinet$K.encryption='owe'
									uci set wireless.wifinet$K.ieee80211w='2'
								else
									uci set wireless.wifinet$K.encryption='none'
								fi
							fi
							case " $legacy_radios " in
							*" $radio "*)
								WLAN_IDX=${radio:5}
								uci set wireless.wifinet$K.ifname="wlan${WLAN_IDX}"
								;;
							*)
								uci set wireless.wifinet$K.ieee80211r='1'
								uci set wireless.wifinet$K.ft_over_ds='1'
								uci set wireless.wifinet$K.ft_psk_generate_local='1'
								;;
							esac
							if [ "$basic_wpad" = 0 ]; then
								uci set wireless.wifinet$K.bss_transition='1'
								uci set wireless.wifinet$K.wnm_sleep_mode='1'
								uci set wireless.wifinet$K.time_advertisement='2'
								uci set wireless.wifinet$K.time_zone='GMT0'
								uci set wireless.wifinet$K.ieee80211k='1'
								uci set wireless.wifinet$K.rrm_neighbor_report='1'
								uci set wireless.wifinet$K.rrm_beacon_report='1'
							fi

							K=$((K+1))
						done
					done
				}

				J=$((J+1))
			done

			uci set fakemesh.default.wifim_md5="${newcfgmd5}"

			uci commit fakemesh
			uci commit wireless
			/etc/init.d/network reload &
		}

		test -f /tmp/fakemesh_lck3/$pid || return 0

		if test $lost_ac -ge $LOST_AC_CNT; then
			logger -t fakemesh "agent_sync_config($pid): recovery from lost_ac=$lost_ac!"
			sleep 5
			/etc/init.d/network reload
			/etc/init.d/dnsmasq reload
			nft list tables 2>/dev/null | grep 'table netdev brmeshfilters_' | while read tb; do
				nft delete $tb
			done
			test -x /etc/init.d/umdns && /etc/init.d/umdns reload
			test -x /etc/init.d/dawn && /etc/init.d/dawn restart
		fi
		lost_ac=0

		rand=$(hexdump -e '"%u"' -n1 /dev/urandom)
		sleep $((50+(rand+0)%20))
		test -f /tmp/fakemesh_lck3/$pid || return 0
	done

	rm -f /tmp/fakemesh_lck3/$pid; rmdir /tmp/fakemesh_lck3
}

agent_keep_alive()
{
	[ "$role" = "agent" ] || return 0

	sta_lost=0

	wbandstr=$(uci show wireless | grep ".band='${band}'$" -m1)
	radio=$(echo "$wbandstr" | cut -d. -f2)
	channel=$(uci get wireless.${radio}.channel)
	test -n "$channel" || return 1

	worker_lock /tmp/fakemesh_lck2 || return 0
	pid=$$

	logger -t fakemesh "agent_keep_alive($pid): started!"
	while :; do
		sleep 10
		sta="$(ubus -S list wpa_supplicant.meshx1)"
		if test -n "$sta"; then
			if [ $(iwinfo meshx1 info | grep -c 'ESSID: unknown') -ge 1 ]; then
				sta_lost=$((sta_lost+1))
				if [ "$sta_lost" -ge 3 ]; then
					logger -t fakemesh "agent_keep_alive($pid): Agent lost connection!"
					rm -f /tmp/fakemesh_lck2/$pid; rmdir /tmp/fakemesh_lck2
					exec /usr/sbin/fakemesh agent_fix_channel &
					return 0
				fi
			elif [ "$(iwinfo meshx1 info | head -n3 | tail -n1 | awk '{print $4}')" != "$channel" ]; then
				logger -t fakemesh "agent_keep_alive($pid): Agent channel changed!"
				worker_unlock
				exec /usr/sbin/fakemesh agent_fix_channel &
				return 0
			fi
		fi
		sleep 30
		test -f /tmp/fakemesh_lck2/$pid || return 0
	done

				worker_unlock
}

agent_fix_channel()
{
	exec /usr/sbin/fakemesh agent_sync_config &

	[ "$role" = "agent" ] || return 0

	wbandstr=$(uci show wireless | grep ".band='${band}'$" -m1)
	radio=$(echo "$wbandstr" | cut -d. -f2)
	channel=$(uci get wireless.${radio}.channel)
	test -n "$channel" || return 1

	worker_lock /tmp/fakemesh_lck1 || return 0
	pid=$$

	logger -t fakemesh "agent_fix_channel($pid): started!"
	while :; do
		sleep 10
		sta="$(ubus -S list wpa_supplicant.meshx1)"
		if test -n "$sta"; then
			chan=$(iwinfo meshx1 scan | grep -F -A1 -B1 "ESSID: \"${Xid}\"" | head -n3 | tail -n1 | grep -io "Channel:.*"| awk '{print $2}')
			if test -n "$chan"; then
				if [ "$chan" != "$channel" ]; then
					logger -t fakemesh "agent_fix_channel($pid): Setting up channel ($chan) for ${radio}"
					uci set wireless.${radio}.channel="$chan"
					test "$chan" -ge "36" -a "$chan" -le "44" || {
						htmode=$(uci get wireless.${radio}.htmode 2>/dev/null)
						if [ "$htmode" = "VHT160" ]; then
							uci set wireless.${radio}.htmode="VHT80"
						elif [ "$htmode" = "HE160" ]; then
							uci set wireless.${radio}.htmode="HE80"
						fi
					}
					uci commit wireless
					/etc/init.d/network reload &
				fi
				logger -t fakemesh "agent_fix_channel($pid): Channel ($chan) for ${radio} ready!"
				break
			fi
		fi
		sleep 20
		test -f /tmp/fakemesh_lck1/$pid || return 0
	done

	worker_unlock

	exec /usr/sbin/fakemesh agent_keep_alive &
}

[ "x$1" = "xagent_lost_ac" ] && {
	agent_lost_ac
	exit 0
}

[ "x$1" = "xagent_fix_channel" ] && {
	agent_fix_channel
	exit 0
}

[ "x$1" = "xagent_keep_alive" ] && {
	agent_keep_alive
	exit 0
}

[ "x$1" = "xagent_sync_config" ] && {
	agent_sync_config
	exit 0
}

agent_reload()
{
	worker_lock /tmp/fakemesh_lck5 || return 0
	sleep 15
	worker_current || return 0
	/etc/init.d/network reload
	/etc/init.d/dnsmasq reload
	worker_current || return 0
	/usr/sbin/fakemesh agent_fix_channel &
}

[ "x$1" = "xagent_reload" ] && {
	agent_reload
	exit 0
}

[ "x$1" = "xgen_config" ] && {
	worker_lock /tmp/fakemesh_lck7 || exit 0
	# http://controller.fakemesh/fakemesh.435ca8a686ae9f07eb4eb67d2216b154
	[ "$role" = "controller" ] && {
		min_snr=$(uci -q get usteer.@usteer[0].min_snr || echo -75)
		roam_trigger=$(uci -q get usteer.@usteer[0].roam_trigger_snr || echo -60)
		roam_scan=$(uci -q get usteer.@usteer[0].roam_scan_snr || echo -65)
		min_connect=$(uci -q get usteer.@usteer[0].min_connect_snr || echo -71)
		signal_diff=$(uci -q get usteer.@usteer[0].signal_diff_threshold || echo 5)
		load_kick=$(uci -q get usteer.@usteer[0].load_kick_enabled || echo 1)
		uci -q set fakemesh.default.min_snr="$min_snr"
		uci -q set fakemesh.default.roam_trigger_snr="$roam_trigger"
		uci -q set fakemesh.default.roam_scan_snr="$roam_scan"
		uci -q set fakemesh.default.min_connect_snr="$min_connect"
		uci -q set fakemesh.default.signal_diff_threshold="$signal_diff"
		uci -q set fakemesh.default.load_kick_enabled="$load_kick"
		uci commit fakemesh

		hash=$(echo -n ${Xid}${Xkey} | md5sum | head -c32)
		ln -s /etc/config/fakemesh /www/fakemesh.$hash 2>/dev/null
		for f in /www/fakemesh.*; do
			[ "$f" != "/www/fakemesh.$hash" ] && rm -f "$f"
		done
	}
	exit 0
}

test -n "${Xid}" || {
	exit 0
}

MACADDR=""
test -e /usr/share/natcapd/board_mac.lua && MACADDR=$(lua /usr/share/natcapd/board_mac.lua)
test -n "$MACADDR" || MACADDR=$(. /lib/functions/system.sh; get_mac_label | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(jsonfilter -i /etc/board.json -e '$["network"]["wan"]["macaddr"]' 2>/dev/null | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(jsonfilter -i /etc/board.json -e '$["network"]["lan"]["macaddr"]' 2>/dev/null | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(cat /sys/class/net/eth0/address 2>/dev/null | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(cat /sys/class/net/eth1/address 2>/dev/null | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(head -c6 /dev/urandom | hexdump -e '/1 "%02X:"' | head -c17)
test -n "$MACADDR" || MACADDR=$(head -c6 /dev/random | hexdump -e '/1 "%02X:"' | head -c17)

if [ "$role" = "controller" ]; then

	test -e /etc/init.d/umdns && {
	mkdir -p /etc/umdns
	ln -s /tmp/fakemesh.umdns.json /etc/umdns 2>/dev/null
	umdns_json=$(controller_announcement) || exit 1
	[ "$(md5sum /tmp/fakemesh.umdns.json 2>/dev/null | head -c32)" = "$(echo "$umdns_json" | md5sum | head -c32)" ] || {
	printf '%s\n' "$umdns_json" >/tmp/fakemesh.umdns.json
	/etc/init.d/umdns restart
	}
	}

	# wireless.radio0.band='2g'
	wbandstr=$(uci show wireless | grep ".band='${band}'$" -m1)
	if test -n "$wbandstr"; then
		radio=$(echo "$wbandstr" | cut -d. -f2) # radio0

		#meshx0
		uci set wireless.meshx0=wifi-iface
		uci set wireless.meshx0.device="${radio}"
		uci set wireless.meshx0.network='lan'
		uci set wireless.meshx0.ifname='meshx0'
		uci set wireless.meshx0.mode='ap'
		uci set wireless.meshx0.wds='1'
		uci set wireless.meshx0.ssid="${Xid}"
		uci set wireless.meshx0.hidden='1'
		uci set wireless.meshx0.wpa_group_rekey='601'
		uci set wireless.meshx0.max_inactivity='301'
		if test -n "${Xkey}"; then
			if [ "$band" = "6g" ]; then
				uci set wireless.meshx0.encryption='sae'
				uci set wireless.meshx0.ieee80211w='2'
			else
				uci set wireless.meshx0.encryption='psk2'
			fi
			uci set wireless.meshx0.key="${Xkey}"
		else
			if [ "$band" = "6g" ]; then
				uci set wireless.meshx0.encryption='owe'
				uci set wireless.meshx0.ieee80211w='2'
			else
				uci set wireless.meshx0.encryption='none'
			fi
		fi
		if [ "$fronthaul_disabled" = "1" ]; then
			uci set wireless.meshx0.disabled='1'
		else
			uci delete wireless.meshx0.disabled 2>/dev/null
		fi

		#meshx1
		uci delete wireless.meshx1 >/dev/null 2>&1
	fi

	uci delete dhcp.meshx0 >/dev/null 2>&1
	uci delete network.meshx0 >/dev/null 2>&1
	uci delete network.meshx0_6 >/dev/null 2>&1

	#re-enable lan
	uci delete network.lan.auto >/dev/null 2>&1
	#re-enable wan
	uci delete network.wan.auto >/dev/null 2>&1
	uci delete network.wan6.auto >/dev/null 2>&1
	#del wan port from br-lan
	lan_idx=0
	while uci get network.@device[$lan_idx] >/dev/null 2>&1 && [ "$(uci get network.@device[$lan_idx].name)" != "br-lan" ]; do lan_idx=$((lan_idx+1)); done
	lan_ports="$(uci get network.@device[$lan_idx].ports 2>/dev/null)"
	wan_port="$(uci get network.wan.device 2>/dev/null)"
	newlan_ports=$(for lp in $lan_ports; do [ "$lp" = "$wan_port" ] || echo "$lp"; done | sort | uniq)
	newlan_ports=$(printf "%s\n" "$newlan_ports" | awk '{ for (i = 1; i <= NF; i++) out = out (out ? " " : "") $i } END { print out }')
	[ "$lan_ports" != "$newlan_ports" ] && {
		uci delete network.@device[$lan_idx].ports >/dev/null 2>&1
		for lp in $newlan_ports; do
			uci add_list network.@device[$lan_idx].ports="$lp"
		done
	}

	#delete meshx0 from lan zone
	lan_idx=0
	while uci get firewall.@zone[$lan_idx] >/dev/null 2>&1 && [ "$(uci get firewall.@zone[$lan_idx].name)" != "lan" ]; do lan_idx=$((lan_idx+1)); done
	lan_net="$(uci get firewall.@zone[$lan_idx].network 2>/dev/null)"
	newlan_net=$(for ln in $lan_net; do [ "$ln" = "meshx0" ] || [ "$ln" = "meshx0_6" ] || echo "$ln"; done | sort | uniq)
	newlan_net=$(printf "%s\n" "$newlan_net" | awk '{ for (i = 1; i <= NF; i++) out = out (out ? " " : "") $i } END { print out }')
	[ "$lan_net" != "$newlan_net" ] && {
		uci delete firewall.@zone[$lan_idx].network >/dev/null 2>&1
		for ln in $newlan_net; do
			uci add_list firewall.@zone[$lan_idx].network="$ln"
		done
		uci commit firewall
	}

	# reload firewall
	uci delete firewall.fakemesh >/dev/null 2>&1 && uci commit firewall

	mkdir -p /usr/share/fakemesh
	cat >/tmp/fakemesh.firewall.include <<EOT
#!/bin/sh
if ! command -v nft &>/dev/null; then
	iptables -t nat -C prerouting_lan_rule -d $access_ip/32 -p tcp --dport 80 -j REDIRECT --to-ports 80 2>/dev/null || \
	iptables -t nat -A prerouting_lan_rule -d $access_ip/32 -p tcp --dport 80 -j REDIRECT --to-ports 80 2>/dev/null
	iptables -t nat -C prerouting_lan_rule -d $access_ip/32 -p tcp --dport 443 -j REDIRECT --to-ports 443 2>/dev/null || \
	iptables -t nat -A prerouting_lan_rule -d $access_ip/32 -p tcp --dport 443 -j REDIRECT --to-ports 443 2>/dev/null
else
	nft_cmds=\$(nft -a list chain inet fw4 dstnat 2>/dev/null | awk -F 'handle ' '/fakemesh/ {print "delete rule inet fw4 dstnat handle "\$2}')
	lan_ifnames=\$(fw4 -q zone lan 2>/dev/null | awk '!/\*/ && !seen[\$0]++ {if(s) s=s", "; s=s"\""\$0"\""} END {print s}')
	if [ -n "\$lan_ifnames" ]; then
		nft_cmds="\${nft_cmds}\${nft_cmds:+
		}insert rule inet fw4 dstnat iifname { \$lan_ifnames } ip daddr $access_ip/32 tcp dport 80 counter redirect to :80 comment \"fakemesh\"
		insert rule inet fw4 dstnat iifname { \$lan_ifnames } ip daddr $access_ip/32 tcp dport 443 counter redirect to :443 comment \"fakemesh\""
	fi
	[ -n "\$nft_cmds" ] && echo "\$nft_cmds" | nft -f - 2>/dev/null
fi
EOT

	ln -s /tmp/fakemesh.firewall.include /usr/share/fakemesh/firewall.include 2>/dev/null
	grep -q "^sh /usr/share/fakemesh/firewall.include" /etc/firewall.include || echo "sh /usr/share/fakemesh/firewall.include" >>/etc/firewall.include

	grep -q "^$access_ip controller.fakemesh ac.fakemesh" /etc/hosts || {
		if grep -q ".* controller.fakemesh ac.fakemesh" /etc/hosts; then
			sed -i "s/.* controller.fakemesh ac.fakemesh/$access_ip controller.fakemesh ac.fakemesh/" /etc/hosts
		else
			echo "$access_ip controller.fakemesh ac.fakemesh" >>/etc/hosts
		fi
		/etc/init.d/dnsmasq reload
	}

	/etc/init.d/firewall reload >/dev/null 2>&1

	/usr/sbin/fakemesh gen_config

	uci changes

	test "$(uci changes 2>/dev/null | grep -c -v "='dhcp'\|='interface'\|='wifi-iface'")" -le 0 && {
		uci revert wireless
		uci revert dhcp
		uci revert network

		exec /usr/sbin/fakemesh agent_sync_config &
		exit 0
	}

	uci commit wireless
	uci commit dhcp
	uci commit network

	/usr/sbin/fakemesh agent_reload &
else
	rm -f /www/fakemesh.*
	/etc/init.d/sta_disable enabled 2>/dev/null && /etc/init.d/sta_disable disable

	test -e /etc/init.d/umdns && {
	rm /tmp/fakemesh.umdns.json 2>/dev/null && \
	/etc/init.d/umdns restart
	}

	# wireless.radio0.band='2g'
	wbandstr=$(uci show wireless | grep ".band='${band}'$" -m1)
	if test -n "$wbandstr"; then
		radio=$(echo "$wbandstr" | cut -d. -f2) # radio0

		#meshx0
		uci set wireless.meshx0=wifi-iface
		uci set wireless.meshx0.device="${radio}"
		uci set wireless.meshx0.network='meshx0'
		uci set wireless.meshx0.ifname='meshx0'
		uci set wireless.meshx0.mode='ap'
		uci set wireless.meshx0.wds='1'
		uci set wireless.meshx0.ssid="${Xid}"
		uci set wireless.meshx0.hidden='1'
		uci set wireless.meshx0.wpa_group_rekey='601'
		uci set wireless.meshx0.max_inactivity='301'
		if test -n "${Xkey}"; then
			if [ "$band" = "6g" ]; then
				uci set wireless.meshx0.encryption='sae'
				uci set wireless.meshx0.ieee80211w='2'
			else
				uci set wireless.meshx0.encryption='psk2'
			fi
			uci set wireless.meshx0.key="${Xkey}"
		else
			if [ "$band" = "6g" ]; then
				uci set wireless.meshx0.encryption='owe'
				uci set wireless.meshx0.ieee80211w='2'
			else
				uci set wireless.meshx0.encryption='none'
			fi
		fi
		if [ "$fronthaul_disabled" = "1" ]; then
			uci set wireless.meshx0.disabled='1'
		else
			uci delete wireless.meshx0.disabled 2>/dev/null
		fi

		#meshx1
		uci set wireless.meshx1=wifi-iface
		uci set wireless.meshx1.device="${radio}"
		uci set wireless.meshx1.network='meshx0'
		uci set wireless.meshx1.ifname='meshx1'
		uci set wireless.meshx1.mode='sta'
		uci set wireless.meshx1.wds='1'
		uci set wireless.meshx1.ssid="${Xid}"
		if test -n "${Xkey}"; then
			if [ "$band" = "6g" ]; then
				uci set wireless.meshx1.encryption='sae'
				uci set wireless.meshx1.ieee80211w='2'
			else
				uci set wireless.meshx1.encryption='psk2'
			fi
			uci set wireless.meshx1.key="${Xkey}"
		else
			if [ "$band" = "6g" ]; then
				uci set wireless.meshx1.encryption='owe'
				uci set wireless.meshx1.ieee80211w='2'
			else
				uci set wireless.meshx1.encryption='none'
			fi
		fi
		if [ "$role" = "wap" ]; then
			uci set wireless.meshx1.disabled='1'
		else
			uci delete wireless.meshx1.disabled 2>/dev/null
		fi

		if [ "$role" = "agent" ] && [ "$(uci get wireless.${radio}.channel 2>/dev/null || echo auto)" = "auto" ]; then
			if [ "$band" = "5g" ]; then
				uci set wireless.${radio}.channel='36'
			else
				uci set wireless.${radio}.channel='1'
			fi
		fi
	fi

	uci set dhcp.meshx0=dhcp
	uci set dhcp.meshx0.ignore='1'

	uci set network.lan.auto='0'

	uci set network.meshx0=interface
	uci set network.meshx0.device="$(uci get network.lan.device)"
	uci set network.meshx0.proto='dhcp'
	uci set network.meshx0.defaultroute='1'
	uci set network.meshx0.metric='10'
	uci set network.meshx0.hostname="MESH-AGENT_$(printf "%s" "$MACADDR" | sed 's/://g' | tr a-f A-F)"

	uci set network.meshx0_6=interface
	uci set network.meshx0_6.proto='dhcpv6'
	uci set network.meshx0_6.device='@meshx0'
	uci set network.meshx0_6.reqaddress='try'
	uci set network.meshx0_6.reqprefix='auto'
	uci set network.meshx0_6.delegate='0'
	uci set network.meshx0_6.hostname="MESH-AGENT_$(printf "%s" "$MACADDR" | sed 's/://g' | tr a-f A-F)"

	#add meshx0 to lan zone
	lan_idx=0
	while uci get firewall.@zone[$lan_idx] >/dev/null 2>&1 && [ "$(uci get firewall.@zone[$lan_idx].name)" != "lan" ]; do lan_idx=$((lan_idx+1)); done
	lan_net="$(uci get firewall.@zone[$lan_idx].network 2>/dev/null)"
	newlan_net=$(for ln in $lan_net meshx0 meshx0_6; do echo "$ln"; done | sort | uniq)
	newlan_net=$(printf "%s\n" "$newlan_net" | awk '{ for (i = 1; i <= NF; i++) out = out (out ? " " : "") $i } END { print out }')
	[ "$lan_net" != "$newlan_net" ] && {
		uci delete firewall.@zone[$lan_idx].network >/dev/null 2>&1
		for ln in $newlan_net; do
			uci add_list firewall.@zone[$lan_idx].network="$ln"
		done
		uci commit firewall
	}

	#disable wan
	uci set network.wan.auto='0' 2>/dev/null
	uci set network.wan6.auto='0' 2>/dev/null
	#add wan port to br-lan
	lan_idx=0
	while uci get network.@device[$lan_idx] >/dev/null 2>&1 && [ "$(uci get network.@device[$lan_idx].name)" != "br-lan" ]; do lan_idx=$((lan_idx+1)); done
	lan_ports="$(uci get network.@device[$lan_idx].ports 2>/dev/null)"
	wan_port="$(uci get network.wan.device 2>/dev/null)"
	newlan_ports=$(for lp in $lan_ports $wan_port; do echo "$lp"; done | sort | uniq)
	newlan_ports=$(printf "%s\n" "$newlan_ports" | awk '{ for (i = 1; i <= NF; i++) out = out (out ? " " : "") $i } END { print out }')
	[ "$lan_ports" != "$newlan_ports" ] && {
		uci delete network.@device[$lan_idx].ports >/dev/null 2>&1
		for lp in $newlan_ports; do
			uci add_list network.@device[$lan_idx].ports="$lp"
		done
	}

	# reload firewall
	uci delete firewall.fakemesh >/dev/null 2>&1 && uci commit firewall

	mkdir -p /usr/share/fakemesh
	cat >/tmp/fakemesh.firewall.include <<EOT
#!/bin/sh
if ! command -v nft &>/dev/null; then
	iptables -t filter -C output_lan_rule -j MARK --set-xmark 0x00010000/0x00010000 2>/dev/null || \
	iptables -t filter -A output_lan_rule -j MARK --set-xmark 0x00010000/0x00010000 2>/dev/null
	iptables -t nat -C zone_lan_postrouting -m mark --mark 0x00010000/0x00010000 -j MASQUERADE 2>/dev/null || \
	iptables -t nat -A zone_lan_postrouting -m mark --mark 0x00010000/0x00010000 -j MASQUERADE 2>/dev/null
else
	nft_cmds=\$(
		nft -a list chain inet fw4 output_lan 2>/dev/null | awk -F 'handle ' '/fakemesh_mark_0x10000/ {print "delete rule inet fw4 output_lan handle "\$2}'
		nft -a list chain inet fw4 srcnat 2>/dev/null | awk -F 'handle ' '/fakemesh_mark_0x10000/ {print "delete rule inet fw4 srcnat handle "\$2}'
	)
	nft_cmds="\${nft_cmds}\${nft_cmds:+
	}insert rule inet fw4 output_lan counter meta mark set mark or 0x10000 comment \"fakemesh_mark_0x10000\""
	lan_ifs=\$(fw4 -q zone lan 2>/dev/null | awk '!/\*/ && !seen[\$0]++ {if(s) s=s", "; s=s"\""\$0"\""} END {print s}')
	if [ -n "\$lan_ifs" ]; then
		nft_cmds="\${nft_cmds}\${nft_cmds:+
		}insert rule inet fw4 srcnat oifname { \$lan_ifs } mark and 0x10000 == 0x10000 counter masquerade comment \"fakemesh_mark_0x10000\""
	fi
	[ -n "\$nft_cmds" ] && echo "\$nft_cmds" | nft -f - 2>/dev/null
fi
EOT
	ln -s /tmp/fakemesh.firewall.include /usr/share/fakemesh/firewall.include 2>/dev/null
	grep -q "^sh /usr/share/fakemesh/firewall.include" /etc/firewall.include || echo "sh /usr/share/fakemesh/firewall.include" >>/etc/firewall.include

	/etc/init.d/firewall reload >/dev/null 2>&1

	uci changes

	test "$(uci changes 2>/dev/null | grep -c -v "='dhcp'\|='interface'\|='wifi-iface'")" -le 0 && {
		uci revert wireless
		uci revert dhcp
		uci revert network

		exec /usr/sbin/fakemesh agent_fix_channel &
		exit 0
	}

	uci commit wireless
	uci commit dhcp
	uci commit network
	sed -i "/.* controller.fakemesh/d" /etc/hosts

	/usr/sbin/fakemesh agent_reload &
fi
