#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG="/usr/nvr/nvrrecord"

init_conf() {
	config_load "nvr"
	config_get "enabled" "config" "enabled"
}


start_service() {
	init_conf
	[ "${enabled}" == "1" ] || exit 0

	procd_open_instance nvr
	procd_set_param command $PROG
	procd_set_param respawn
	procd_close_instance
}

service_triggers() { 
	procd_add_reload_trigger "nvr" 
}

reload_service() {
	stop
	start
}

stop_service() {
	init_conf
	service_stop $PROG
}
