#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
NAME=fail2banop
 
get_config() {
  config_get_bool enabled $1 enabled 0
}

start_service() { 
  config_load "$NAME"
  config_foreach get_config "$NAME"
  [ $enabled != 1 ] && return 1

  procd_open_instance
  procd_set_param command /usr/sbin/fail2banop
  procd_set_param stderr 1
  procd_set_param respawn
  procd_close_instance
}

service_triggers() {
  procd_add_reload_trigger "$NAME"
}

