#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2010 OpenWrt.org

START=99
STOP=15

NanoHatOLED="/usr/share/NanoHatOLED/NanoHatOLED"

start() {
		
		# 启动 OLED
		$NanoHatOLED  > /dev/null 2>&1 &

}

stop() {
		# 关闭 OLED
		kill -9 `ps w|grep -E "NanoHatOLED|bakebit_nanohat_oled"|grep -v "grep"|awk '{print $1}'` 2>/dev/null

}