

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.3-r1
PKG_RELEASE:=

LUCI_TITLE:=LuCI support for xunyou
LUCI_PKGARCH:=all
LUCI_DEPENDS:=xunyou

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


