include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=20221110
PKG_MAINTAINER:=xiaobao <xiaobao@linkease.com>

LUCI_TITLE:=LuCI support for mymind
LUCI_DESCRIPTION:=all

LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

