#!/bin/sh
chmod +x /etc/init.d/netspeedtest  >/dev/null 2>&1
[  `uci -q get netspeedtest.netspeedtest` ]  || uci set netspeedtest.netspeedtest=netspeedtest
[  `uci -q get netspeedtest.speedtestiperf3` ] || uci set netspeedtest.speedtestiperf3=speedtestiperf3
[  `uci -q get netspeedtest.speedtestport` ]  || uci set netspeedtest.speedtestport=speedtestport
[  `uci -q get netspeedtest.speedtestwan` ]  || uci set netspeedtest.speedtestport=speedtestwan

rm -rf /tmp/luci-modulecache /tmp/luci-indexcache*
exit 0
