#!/bin/sh

# needed for "Save and Apply" to restart msd_lite
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@msd_lite[-1]
	add ucitrack msd_lite
	set ucitrack.@msd_lite[-1].init=msd_lite
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
