#!/bin/sh
if [ "$(uci -q get snmpd.general.network)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		add_list snmpd.general.network=lan
		set snmpd.@system[0].sysName="OpenMPTCProuter"
		set snmpd.general.enabled=0
		commit snmpd
	EOF
fi

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@snmpd[-1]
	add ucitrack snmpd
	set ucitrack.@snmpd[-1].init=snmpd
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0