#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoe-relay[-1]
	add ucitrack pppoe-relay
	set ucitrack.@pppoe-relay[-1].init=pppoe-relay
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache /tmp/luci-indexcache.*
rm -rf /tmp/luci-modulecache/
killall -HUP rpcd 2>/dev/null

exit 0
