#!/bin/sh

CONFIG_NAME='tinyfilemanager'
eval "$(sed -En '/^\$CONFIG\s*=\s*/{s|^\$CONFIG\s*=\s*|CONFIG=|p}' $CONF | tr -d '\r')"

if [ -n "$CONFIG" ]; then
	uci set $CONFIG_NAME.@$TYPEDSECTION[0].defconf="$CONFIG"
	[ -z "$(uci changes $CONFIG_NAME)" ] || uci commit $CONFIG_NAME
fi

while :; do
	sleep 86400
done
