#!/bin/sh

# uhttpd
uci -q get uhttpd.main.index_page|grep -i 'index.php' >/dev/null || uci add_list uhttpd.main.index_page='index.php'
uci -q get uhttpd.main.interpreter|grep -i '.php=/usr/bin/php-cgi' >/dev/null || uci add_list uhttpd.main.interpreter='.php=/usr/bin/php-cgi'
uci changes uhttpd|grep . >/dev/null && uci commit uhttpd
/etc/init.d/uhttpd reload

# nginx
[ -n "$(command -v nginx)" ] && /etc/init.d/nginx reload

exit 0
