#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	state=`pgrep -f "/usr/bin/pushbot/pushbot"`
	if [ ! -z "$state" ]; then
		restart
	else
		/usr/bin/pushbot/pushbot </dev/null >/dev/null 2>&1 &
	fi
	echo "pushbot is starting now ..."
}

stop() {
	kill -9 `pgrep -f "/usr/bin/pushbot/pushbot"` 2>/dev/null
	echo "pushbot exit ..."
}

restart(){
	stop
	sleep 1
	start
	echo "restarted."
}
