coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 0%
        informational: false

ignore:
  - "src/third/"
  - "test/"

flags:
  unittests:
    paths:
      - src/
  unittests-standalone:
    paths:
      - src/
  integration-cache:
    paths:
      - src/
  integration-no-cache:
    paths:
      - src/
  proxy-lifecycle:
    paths:
      - src/
  openwrt-qemu:
    paths:
      - src/

flag_management:
  default_rules:
    carryforward: false
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 80%
        threshold: 0%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
