#!/bin/sh

[ ! -f /etc/config/mmdvm ] && touch /etc/config/mmdvm
[ -z `uci -q get mmdvm.POCSAG.Enable` ] && {
	uci set mmdvm.POCSAG=mmdvmhost
	uci set mmdvm.POCSAG.Enable=0
	uci commit mmdvm
}

ENABLE=$(uci -q get mmdvm.POCSAG.Enable)
if [ "$ENABLE" != "1" ]; then
    /etc/init.d/dapnetgateway stop
    /etc/init.d/dapnetgateway disable
fi

exit 0
