# SPDX-License-Identifier: GPL-3.0
#
# Copyright (C) 2021-2025  sirpdboy  <herboy2008@gmail.com> https://github.com/sirpdboy/luci-app-netdata

include $(TOPDIR)/rules.mk


LUCI_TITLE:=LuCI app for netdata
LUCI_DEPENDS:=+netdata

PKG_NAME:=luci-app-netdata
PKG_VERSION:=2.0.4
PKG_RELEASE:=20251106
PKG_LICENSE:=GPL-3.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
