#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@supervisord[-1]
	add ucitrack supervisord
	set ucitrack.@supervisord[-1].init=supervisord
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
