#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# gen-dae-config.sh - build /etc/dae/config.dae from the dae UCI form sections,
# validate with `dae validate`, then overwrite + hot reload only on success.
#
#   generate   read UCI -> render config.dae -> validate -> overwrite + hot reload
#   import     parse existing config.dae subscription{}/node{} -> fill UCI form
#
# UCI model (package dae):
#   config subscription      tag/url, enabled
#   config node              tag/link, enabled
#   config group             name/policy, list filter_sub, list filter_node
#   config routing 'routing' private_direct/cn_direct/block_ads/fallback, list custom
#   config dns 'dns'         cn_upstream/fallback_upstream

. /lib/functions.sh

CONFIG_DAE="/etc/dae/config.dae"
TMP_GEN="/tmp/dae-gen.dae"
DAE_BIN="/usr/bin/dae"
DAE_INITD="/etc/init.d/dae"

# dae single-quoted strings have no escaping; strip quotes/newlines defensively.
sanitize() {
	printf '%s' "$1" | tr -d "'" | tr -d '\n\r'
}

# ===================== generate =====================

SUB_BUF=""
NODE_BUF=""
GROUP_BUF=""
FIRST_GROUP=""

emit_sub() {
	local s="$1" tag url enabled
	config_get tag "$s" tag ""
	config_get url "$s" url ""
	config_get_bool enabled "$s" enabled 1
	[ "$enabled" = "1" ] || return 0
	url="$(sanitize "$url")"
	[ -n "$url" ] || return 0
	tag="$(sanitize "$tag")"
	if [ -n "$tag" ]; then
		SUB_BUF="${SUB_BUF}    ${tag}: '${url}'
"
	else
		SUB_BUF="${SUB_BUF}    '${url}'
"
	fi
}

emit_node() {
	local s="$1" tag link enabled
	config_get tag "$s" tag ""
	config_get link "$s" link ""
	config_get_bool enabled "$s" enabled 1
	[ "$enabled" = "1" ] || return 0
	link="$(sanitize "$link")"
	[ -n "$link" ] || return 0
	tag="$(sanitize "$tag")"
	if [ -n "$tag" ]; then
		NODE_BUF="${NODE_BUF}    ${tag}: '${link}'
"
	else
		NODE_BUF="${NODE_BUF}    '${link}'
"
	fi
}

emit_group() {
	local s="$1" name policy
	config_get name "$s" name ""
	config_get policy "$s" policy "min_moving_avg"
	name="$(sanitize "$name")"
	[ -n "$name" ] || return 0
	[ -n "$FIRST_GROUP" ] || FIRST_GROUP="$name"

	GROUP_BUF="${GROUP_BUF}    ${name} {
"
	# multiple filter lines = OR; subtag() picks subscriptions, name() picks nodes
	config_list_foreach "$s" filter_sub _collect_subs
	if [ -n "$SUBS_ACC" ]; then
		GROUP_BUF="${GROUP_BUF}        filter: subtag(${SUBS_ACC})
"
	fi
	config_list_foreach "$s" filter_node _collect_nodes
	if [ -n "$NODES_ACC" ]; then
		GROUP_BUF="${GROUP_BUF}        filter: name(${NODES_ACC})
"
	fi
	GROUP_BUF="${GROUP_BUF}        policy: ${policy}
    }
"
	SUBS_ACC=""
	NODES_ACC=""
}

SUBS_ACC=""
NODES_ACC=""
_collect_subs() {
	local v="$(sanitize "$1")"
	[ -n "$v" ] || return 0
	if [ -n "$SUBS_ACC" ]; then SUBS_ACC="${SUBS_ACC}, ${v}"; else SUBS_ACC="$v"; fi
}
_collect_nodes() {
	local v="$(sanitize "$1")"
	[ -n "$v" ] || return 0
	if [ -n "$NODES_ACC" ]; then NODES_ACC="${NODES_ACC}, ${v}"; else NODES_ACC="$v"; fi
}

generate() {
	config_load dae

	# global overridable knobs (fall back to defaults)
	local dial_mode log_level wan_interface lan_interface
	config_get dial_mode config dial_mode "domain"
	config_get log_level config log_level "info"
	config_get wan_interface config wan_interface "auto"
	config_get lan_interface config lan_interface ""

	SUB_BUF=""; NODE_BUF=""; GROUP_BUF=""; FIRST_GROUP=""
	config_foreach emit_sub subscription
	config_foreach emit_node node
	config_foreach emit_group group

	# fall back to a default group when none defined
	if [ -z "$GROUP_BUF" ]; then
		GROUP_BUF="    proxy {
        policy: min_moving_avg
    }
"
		FIRST_GROUP="proxy"
	fi

	# routing / dns singletons
	local private_direct cn_direct block_ads fallback cn_up fb_up
	config_get_bool private_direct routing private_direct 1
	config_get_bool cn_direct routing cn_direct 1
	config_get_bool block_ads routing block_ads 0
	config_get fallback routing fallback "$FIRST_GROUP"
	[ -n "$fallback" ] || fallback="$FIRST_GROUP"
	fallback="$(sanitize "$fallback")"
	config_get cn_up dns cn_upstream "udp://dns.alidns.com:53"
	config_get fb_up dns fallback_upstream "tcp+udp://dns.google:53"
	cn_up="$(sanitize "$cn_up")"
	fb_up="$(sanitize "$fb_up")"

	{
		echo "# Auto-generated by luci-app-daede form. Manual edits are overwritten on next save."
		echo "global {"
		echo "    tproxy_port: 12345"
		echo "    tproxy_port_protect: true"
		echo "    log_level: ${log_level}"
		[ -n "$lan_interface" ] && echo "    lan_interface: ${lan_interface}"
		echo "    wan_interface: ${wan_interface}"
		echo "    auto_config_kernel_parameter: true"
		echo "    dial_mode: ${dial_mode}"
		echo "    tcp_check_url: 'http://cp.cloudflare.com,1.1.1.1,2606:4700:4700::1111'"
		echo "    udp_check_dns: 'dns.google:53,8.8.8.8,2001:4860:4860::8888'"
		echo "    check_interval: 30s"
		echo "    check_tolerance: 50ms"
		echo "}"
		echo ""

		if [ -n "$SUB_BUF" ]; then
			echo "subscription {"
			printf '%s' "$SUB_BUF"
			echo "}"
			echo ""
		fi

		if [ -n "$NODE_BUF" ]; then
			echo "node {"
			printf '%s' "$NODE_BUF"
			echo "}"
			echo ""
		fi

		echo "dns {"
		echo "    upstream {"
		echo "        cndns: '${cn_up}'"
		echo "        fallbackdns: '${fb_up}'"
		echo "    }"
		echo "    routing {"
		echo "        request {"
		echo "            qname(geosite:cn) -> cndns"
		echo "            fallback: fallbackdns"
		echo "        }"
		echo "    }"
		echo "}"
		echo ""

		echo "group {"
		printf '%s' "$GROUP_BUF"
		echo "}"
		echo ""

		echo "routing {"
		echo "    pname(NetworkManager) -> direct"
		[ "$private_direct" = "1" ] && echo "    dip(geoip:private) -> direct"
		if [ "$cn_direct" = "1" ]; then
			echo "    dip(geoip:cn) -> direct"
			echo "    domain(geosite:cn) -> direct"
		fi
		[ "$block_ads" = "1" ] && echo "    domain(geosite:category-ads-all) -> block"
		config_list_foreach routing custom _emit_custom
		echo "    fallback: ${fallback}"
		echo "}"
	} > "$TMP_GEN"
	chmod 600 "$TMP_GEN"  # dae rejects world/group-accessible config files

	# overwrite live config only if validation passes
	local out
	out="$("$DAE_BIN" validate -c "$TMP_GEN" 2>&1)"
	if [ $? -ne 0 ]; then
		echo "validate failed: $(echo "$out" | head -1)" >&2
		rm -f "$TMP_GEN"
		return 1
	fi

	mkdir -p /etc/dae
	cat "$TMP_GEN" > "$CONFIG_DAE"
	chmod 600 "$CONFIG_DAE"
	rm -f "$TMP_GEN"

	if /usr/bin/pgrep -x dae >/dev/null 2>&1; then
		"$DAE_INITD" hot_reload >/dev/null 2>&1
	fi
	echo "ok"
	return 0
}

_emit_custom() {
	local line="$(printf '%s' "$1" | tr -d '\n\r')"
	[ -n "$line" ] || return 0
	echo "    ${line}"
}

# ===================== import =====================
# Fill the UCI form from an existing config.dae subscription{}/node{} block.
# Idempotent: wipe same-type sections first, then rebuild from file.

import_block() {
	# $1=block name (subscription|node)  $2=uci section type  $3=link/url field
	local block="$1" stype="$2" field="$3"
	awk -v blk="$block" '
		$0 ~ "^[[:space:]]*"blk"[[:space:]]*\\{" { inb=1; next }
		inb && /^[[:space:]]*\}/ { inb=0 }
		inb { print }
	' "$CONFIG_DAE" 2>/dev/null | while IFS= read -r raw; do
		# drop comment, trim
		line="$(printf '%s' "$raw" | sed 's/#.*$//' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
		[ -n "$line" ] || continue
		tag=""; val=""
		case "$line" in
			\'*|\"*)
				# starts with a quote -> untagged link
				val="$line"
				;;
			[A-Za-z0-9_]*:*)
				# identifier ':' link -> tagged (split on first colon)
				tag="$(printf '%s' "$line" | sed "s/[[:space:]]*:.*//")"
				val="$(printf '%s' "$line" | sed "s/^[^:]*:[[:space:]]*//")"
				;;
			*)
				val="$line"
				;;
		esac
		# strip surrounding quotes
		val="$(printf '%s' "$val" | sed "s/^['\"]//; s/['\"]$//")"
		[ -n "$val" ] || continue
		# skip dae example placeholders (ss://LINK, server-ip:port, localhost:1080 ...)
		case "$val" in
			*://LINK|*LINK*|*server-ip*|*://localhost:*|*example.com*) continue ;;
		esac
		sid="$(uci add dae "$stype")"
		[ -n "$tag" ] && uci set "dae.$sid.tag=$tag"
		uci set "dae.$sid.$field=$val"
		uci set "dae.$sid.enabled=1"
	done
}

do_import() {
	[ -f "$CONFIG_DAE" ] || { echo "no config.dae" >&2; return 1; }
	while uci -q delete dae.@subscription[0] >/dev/null 2>&1; do :; done
	while uci -q delete dae.@node[0] >/dev/null 2>&1; do :; done
	import_block subscription subscription url
	import_block node node link
	uci commit dae
	echo "ok"
}

# ===================== entry =====================

case "$1" in
	generate) generate ;;
	import)   do_import ;;
	*) echo "usage: $0 {generate|import}" >&2; exit 2 ;;
esac
