#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
rm -fr /tmp/luci-indexcache* /tmp/luci-modulecache
[ -x ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_postinst $0 $@
