#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autorepeater[-1]
	add ucitrack autorepeater
	set ucitrack.@autorepeater[-1].init=autorepeater
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
