#!/bin/sh /etc/rc.common

START=90
STOP=15

start() {
	config_load uuplugin
	local enable
	config_get_bool enable uuplugin enabled
	if [ "$enable" -eq 0 ]; then
	  stop
	else
	  /usr/bin/uuplugin/uuplugin >/dev/null 2>&1 &
	fi
}

stop() {
	config_load uuplugin
	local enabled
	config_get_bool enabled uuplugin enabled
	kill -9 `pgrep -f "/usr/bin/uuplugin/uuplugin"` 2>/dev/null
}
