#!/bin/sh

uci -q batch <<-EOF >/dev/null
    delete firewall.bmtedge
    set firewall.bmtedge=rule
    set firewall.bmtedge.name="bmtedge"
    set firewall.bmtedge.target="ACCEPT"
    set firewall.bmtedge.src="wan"
    set firewall.bmtedge.dest_port="1024-65535"
    set firewall.bmtedge.enabled="0"
    commit firewall
EOF

exit 0
