#!/bin/sh
chmod +x  /etc/init.d/autotimeset /usr/bin/timesethandler /etc/init.d/autotimesetrun
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autotimeset[-1]
	add ucitrack autotimeset 
	set ucitrack.@autotimeset[-1].init="autotimeset"
	commit ucitrack
	delete ucitrack.@autotimesetrun[-1]
	add ucitrack autotimesetrun
	set ucitrack.@autotimesetrun[-1].init=autotimesetrun
	commit ucitrack
EOF
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache*
exit 0