#!/bin/sh
chmod +x  /etc/init.d/timecontrol /usr/bin/timecontrol*
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@timecontrol[-1]
	add ucitrack timecontrol
	set ucitrack.@timecontrol[-1].init=timecontrol
	commit ucitrack
EOF

[ -s /etc/config/timecontrol ] ||  echo "config timecontrol" > /etc/config/timecontrol
rm -f /tmp/luci-indexcache
exit 0
