include $(TOPDIR)/rules.mk

LUCI_TITLE:=LingTi Game Acc
LUCI_DEPENDS:=+lingtigameacc +luci-base
LUCI_PKGARCH:=all

PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
