# Copyright (C) 2020-2023 Hyy2001X <https://github.com/Hyy2001X>

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-natter
PKG_VERSION:=1.1
PKG_RELEASE:=4

LUCI_TITLE:=LuCI Support for Natter
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+natter

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
