#
# Copyright (C) 2019-2020 <wsdosh@gmail.com>
#
# This is free software, licensed under the Apache License, Version 3.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-shortcutmenu
LUCI_TITLE:=LuCI Support for shortcutmenu
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=v0.0.5
PKG_LICENSE:=AGPL-3.0
PKG_MAINTAINER:=<https://github.com/doushang/luci-app-shortcutmenu>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
