# SPDX-License-Identifier: MIT

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Tower - manage subscriptions and generate client configs
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+tower

PKG_NAME:=luci-app-tower
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
