#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.luci_app_ipsec_server
	set firewall.luci_app_ipsec_server=include
	set firewall.luci_app_ipsec_server.type=script
	set firewall.luci_app_ipsec_server.path=/var/etc/ipsecvpn.include
EOF

if [ -x "/sbin/fw3" ] && [ ! -L "/sbin/fw3" ]; then
	uci -q set firewall.luci_app_ipsec_server.reload='1'
else
	uci -q delete firewall.luci_app_ipsec_server.reload
	uci -q delete firewall.luci_app_ipsec_server.fw4_compatible
fi
uci commit firewall

/etc/init.d/ipsec disable 2>/dev/null
/etc/init.d/ipsec stop 2>/dev/null
/etc/init.d/xl2tpd disable 2>/dev/null
/etc/init.d/xl2tpd stop 2>/dev/null
rm -rf /tmp/luci-*cache
exit 0
