#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.wrtbwmon
	set firewall.wrtbwmon=include
	set firewall.wrtbwmon.type=script
	set firewall.wrtbwmon.path='/etc/wrtbwmon.include'
EOF

if [ -x "/sbin/fw3" ] && [ ! -L "/sbin/fw3" ]; then
	uci -q set firewall.wrtbwmon.reload='1'
else
	uci -q delete firewall.wrtbwmon.reload
	uci -q delete firewall.wrtbwmon.fw4_compatible
fi
uci commit firewall

/etc/init.d/wrtbwmon enable
/etc/init.d/wrtbwmon start
exit 0
