#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.luci_app_softethervpn
	set firewall.luci_app_softethervpn=include
	set firewall.luci_app_softethervpn.type=script
	set firewall.luci_app_softethervpn.path=/var/etc/luci-app-softethervpn.include
	set firewall.luci_app_softethervpn.reload=1
EOF

/etc/init.d/softethervpnserver stop 2>/dev/null
/etc/init.d/softethervpnserver disable 2>/dev/null

rm -rf /tmp/luci-*cache
exit 0
