#!/bin/sh
# Migration script for fchomo inbound
# Used to migrate LuCI application inbound option.

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

CONF=fchomo

config_load "$CONF"

# isDefined <section> <option>
isDefined() {
	local opt=CONFIG_${1}_${2};

	eval "[ -n \"\${$opt+x}\" ] && return 0 || return 1"
}

migrate() {
	# tuic_max_idle_time -> max_idle_time
	if isDefined "$1" tuic_max_idle_time; then
		local tuic_max_idle_time
		config_get tuic_max_idle_time "$1" tuic_max_idle_time ""
		uci_remove "$CONF" "$1" tuic_max_idle_time
		uci_set "$CONF" "$1" max_idle_time "$tuic_max_idle_time"
	fi

	# hysteria_up_mbps -> brutal_up_mbps
	if isDefined "$1" hysteria_up_mbps; then
		local hysteria_up_mbps
		config_get hysteria_up_mbps "$1" hysteria_up_mbps ""
		uci_remove "$CONF" "$1" hysteria_up_mbps
		uci_set "$CONF" "$1" brutal_up_mbps "$hysteria_up_mbps"
	fi

	# hysteria_down_mbps -> brutal_down_mbps
	if isDefined "$1" hysteria_down_mbps; then
		local hysteria_down_mbps
		config_get hysteria_down_mbps "$1" hysteria_down_mbps ""
		uci_remove "$CONF" "$1" hysteria_down_mbps
		uci_set "$CONF" "$1" brutal_down_mbps "$hysteria_down_mbps"
	fi

	# hysteria_ignore_client_bandwidth -> brutal_ignore_client_bandwidth
	if isDefined "$1" hysteria_ignore_client_bandwidth; then
		local hysteria_ignore_client_bandwidth
		config_get hysteria_ignore_client_bandwidth "$1" hysteria_ignore_client_bandwidth ""
		uci_remove "$CONF" "$1" hysteria_ignore_client_bandwidth
		uci_set "$CONF" "$1" brutal_ignore_client_bandwidth "$hysteria_ignore_client_bandwidth"
	fi

	# plugin -> plugin_type
	if isDefined "$1" plugin && ! isDefined "$1" plugin_type; then
		local plugin
		config_get plugin "$1" plugin ""
		uci_set "$CONF" "$1" plugin "1"
		uci_set "$CONF" "$1" plugin_type "$plugin"
	fi
}

config_foreach migrate inbound

uci_commit "$CONF"

exit 0
