#!/bin/sh

default_proxy=$(uci -q get fchomo.routing.default_proxy)
if [ -n "$default_proxy" ]; then
	uci -q batch <<-EOF >"/dev/null"
		delete fchomo.routing.default_proxy
		set fchomo.routing.client_enabled="1"
		set fchomo.autogened_final_host="rules"
		set fchomo.autogened_final_host.label="Auto Generated Final"
		set fchomo.autogened_final_host.entry="MATCH,$default_proxy"
		commit fchomo
	EOF
fi

exit 0
