
include $(TOPDIR)/rules.mk

LUCI_TITLE:=iStoreNext
LUCI_DESCRIPTION:=LuCI module for iStoreNext
PKG_VERSION:=0.0.4
PKG_RELEASE:=1
LUCI_DEPENDS:=+luci-nginxer

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
