#!/bin/sh

APK=false
PKG_BASE=usr/lib/opkg/info
PKG_EXT=control

[ -s /etc/apk/arch ] && {
    APK=true
    PKG_BASE=lib/apk/packages
    PKG_EXT=list
}

nonconf_files_of_pkg() {
    local pkgname="$1"
    if [ -s /rom/$PKG_BASE/${pkgname}.conffiles ]; then
        grep -hvxFf /rom/$PKG_BASE/${pkgname}.conffiles \
            /rom/$PKG_BASE/${pkgname}.list
    else
        cat /rom/$PKG_BASE/${pkgname}.list
    fi
}

reset_pkg() {
    local pkgname="$1"
    local line
    echo "${pkgname}" | grep -q '^kernel$
^libc$
^libgcc1$
^libatomic1$
^busybox$' && return
    if [ -f /rom/$PKG_BASE/${pkgname}.$PKG_EXT -a \
            \( -e /overlay/upper/$PKG_BASE/${pkgname}.$PKG_EXT -o \
             -e /ext_overlay/upper/$PKG_BASE/${pkgname}.$PKG_EXT \) ]; then
        echo "reset ${pkgname}"
        if [ -f /rom/$PKG_BASE/${pkgname}.list ]; then
            nonconf_files_of_pkg "${pkgname}" | while read; do
                line="$REPLY"
                rm -f "/overlay/upper/${line}" "/ext_overlay/upper/${line}"
            done
            rm -f /overlay/upper/$PKG_BASE/${pkgname}.list /ext_overlay/upper/$PKG_BASE/${pkgname}.list
        fi
    fi
}

ls_all_rom_pkgs() {
	( cd /rom/$PKG_BASE ; find . -maxdepth 1 -name "*.$PKG_EXT" | sed -E 's#./(.*).'"$PKG_EXT"'#\1#g' )
}

reset_all_rom() {
    local line
    ls_all_rom_pkgs | while read; do
        line="$REPLY"
        reset_pkg "$line"
    done
}

reset_all_rom

if $APK; then
    rm -f /overlay/upper/etc/uci-defaults/.upgrading /ext_overlay/upper/etc/uci-defaults/.upgrading
    touch /overlay/upper/etc/uci-defaults/.upgrading 2>/dev/null
else
    rm -f /overlay/upper/usr/lib/opkg/.upgrading /ext_overlay/upper/usr/lib/opkg/.upgrading
    touch /overlay/upper/usr/lib/opkg/.upgrading 2>/dev/null
fi

echo "done, please reboot, it will reboot in 10s"

sleep 10
reboot

