#!/bin/sh /etc/rc.common

#
# (c) 2010-2024 Cezary Jackiewicz <cezary@eko.one.pl>
#

START=99

start() {
	PORT=$(uci -q get 3ginfo.@3ginfo[0].http_port)
	[ -z "$PORT" ] && PORT=81
	uhttpd -E /index.html -x /cgi-bin -h /usr/share/3ginfo/html -p 0.0.0.0:$PORT -i .sh=/bin/sh > /dev/null 2>&1
}
