#!/bin/sh /etc/rc.common

START=79
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/uhttpd -f -h /demo -r Test -x /cgi-bin/luci/istorenext/cgi-bin -u /ubus -t 360 -T 30 -k 20 -A 1 -n 50 -N 100 -R -p 0.0.0.0:8080
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}
