#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.ThemeDog >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.ThemeDog=/luci-static/dog
		set luci.main.mediaurlbase=/luci-static/dog
		commit luci
	EOF
fi

exit 0
