#!/bin/sh

uci -q batch <<-EOF >/dev/null
        delete ucitrack.@v2raya[-1]
        add ucitrack v2raya
        set ucitrack.@v2raya[-1].init=v2raya
        commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
