#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.zerotier
	set firewall.zerotier=include
	set firewall.zerotier.type=script
	set firewall.zerotier.path=/etc/zerotier.start
EOF

if [ -x "/sbin/fw3" ] && [ ! -L "/sbin/fw3" ]; then
	uci -q set firewall.zerotier.reload='1'
else
	uci -q delete firewall.zerotier.reload
	uci -q delete firewall.zerotier.fw4_compatible
fi
uci commit firewall

rm -f /tmp/luci-indexcache
exit 0
