include $(TOPDIR)/rules.mk

PKG_VERSION:=1.2.1

LUCI_TITLE:=LuCI Support for momo
LUCI_DEPENDS:=+luci-base +momo

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature