include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.5

LUCI_TITLE:=LuCI Support for momo
LUCI_DEPENDS:=+luci-base +momo

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature