#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@natter[-1]
	add ucitrack natter
	set ucitrack.@natter[-1].init=natter
	commit ucitrack
	
	delete firewall.natter
	set firewall.natter=include
	set firewall.natter.type=script
	set firewall.natter.path=/var/etc/natter.include
	set firewall.natter.reload=1
	commit firewall
EOF

exit 0