#!/bin/sh
uci get xray_core.@general[-1] >/dev/null 2>&1 || uci add xray_core general >/dev/null 2>&1
uci commit xray_core
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@xray_core[-1]
	add ucitrack xray_core
	set ucitrack.@xray_core[-1].init=xray_core
	commit ucitrack
EOF
exit 0
