

include $(TOPDIR)/rules.mk

LUCI_DEPENDS:=xunyou
PKG_VERSION:=1.0.0-20210912
PKG_RELEASE:=

LUCI_TITLE:=LuCI support for xunyou
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


