#!/bin/sh /etc/rc.common
# 
# Copyright 2019-2020 Michael BD7MQB <bd7mqb@qq.com>
# This is free software, licensed under the GNU GENERAL PUBLIC LICENSE, Version 2.0
# 

START=94
APP=P25Parrot
USE_PROCD=1
LOG_PATH=/var/log/mmdvm
PORT=42011
EXTRA_COMMANDS="status"                                                                                        
EXTRA_HELP="	status	Display status of ${APP}" 

start_service() {
    [ -d $LOG_PATH ] || mkdir -m 0775 -p $LOG_PATH
    ubus -t 60 wait_for network.interface network.wireless 2>/dev/null

    logger -s -t mmdvm "Starting $APP Service..."
    procd_open_instance
    procd_set_param respawn
    procd_set_param command /usr/sbin/$APP $PORT
    procd_close_instance
}
 
stop_service() {
    logger -s -t mmdvm "Stoping $APP Service..."
}

status() {
    local PID=`pidof ${APP}`
    local STATUS
    if [ ! ${PID} ]; then
        STATUS="Stopped"
    else
        STATUS="Started - PID ${PID}"
    fi

    echo "${APP}:	[${STATUS}]"
}