#!/bin/sh /etc/rc.common

# shellcheck disable=SC2034
START=99

boot() {
	XBOOT=1 start
}

start() {
	touch /tmp/fakemesh.ac.config
	ln -s /tmp/fakemesh.ac.config /etc/config/fakemeshac 2>/dev/null

	/usr/sbin/fakemesh || return $?
	/usr/sbin/fakemesh band_steer_helper_switch
}

restart() {
	XRELOAD=1 start
}
