#!/bin/sh
#
# Load the glorytun config
#
# Author: Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
# Released under GPL 3 or later

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0

. /lib/functions.sh
. /lib/functions/network.sh

set_default() {
    local localip
    local remoteip
    local config="$1"
    local iface
    config_get enable "$config" enable
    config_get iface "$config" dev
    [ "$iface" = "$DEVICE" ] && [ "$enable" = "1" ] && {
	config_get localip "$config" localip
	config_get remoteip "$config" remoteip
	[ "$remoteip" != "" ] && [ "$localip" != "" ] &&  ifconfig $DEVICE $localip pointopoint $remoteip up
    }
}

config_load glorytun
config_foreach set_default glorytun
